#ifndef VIBRATO_H
#define VIBRATO_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

struct NativeTokenizer;

struct VibratoBuffer {
  uint8_t *data_ptr;
  uintptr_t length;
};

struct TokenC {
  char *surface;
  char *lex_type;
  char *features;
  uint32_t word_id;
  uint16_t left_id;
  uint16_t right_id;
  int16_t word_cost;
  int32_t total_cost;
};

struct TokenCArray {
  TokenC *data;
  uintptr_t len;
};

extern "C" {

char *vibrato_get_last_error();

NativeTokenizer *vibrato_create(const uint8_t *bytes_ptr,
                                uintptr_t length,
                                const bool *ignore_space,
                                const uintptr_t *max_grouping_len);

NativeTokenizer *vibrato_create_from_textdict(const uint8_t *lex_ptr,
                                              uintptr_t lex_len,
                                              const uint8_t *matrix_ptr,
                                              uintptr_t matrix_len,
                                              const uint8_t *char_ptr,
                                              uintptr_t char_len,
                                              const uint8_t *unk_ptr,
                                              uintptr_t unk_len,
                                              const bool *ignore_space,
                                              const uintptr_t *max_grouping_len);

VibratoBuffer *vibrato_compile_dict(const uint8_t *lex_ptr,
                                    uintptr_t lex_len,
                                    const uint8_t *matrix_ptr,
                                    uintptr_t matrix_len,
                                    const uint8_t *char_ptr,
                                    uintptr_t char_len,
                                    const uint8_t *unk_ptr,
                                    uintptr_t unk_len);

TokenCArray vibrato_tokenize(NativeTokenizer *tokenizer_ptr, const char *text);

void vibrato_free_tokenizer(NativeTokenizer *tokenizer_ptr);

void vibrato_free_string(char *ptr);

void vibrato_free_buffer(VibratoBuffer *buffer_ptr);

void vibrato_free_token_array(TokenCArray array);

}  // extern "C"

#endif  // VIBRATO_H
